import type { RecipeListItem } from '@/actions/recipes'

const BASE = new Date('2024-09-01')

export const DEMO_RECIPES: RecipeListItem[] = [
  {
    id: 'demo-1',
    userId: 'demo',
    title: 'Pasta Carbonara',
    subtitle: 'Roman classic with eggs, pecorino and guanciale',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    imageTone: '#C4A882',
    cookTime: 25,
    difficulty: 'Easy',
    tags: ['Italian', 'Quick'],
    isFavorite: false,
    isPublic: false,
    createdAt: BASE,
    updatedAt: BASE,
    ingredients: [
      { id: 'di-1-1', recipeId: 'demo-1', qty: '400', unit: 'g',  item: 'spaghetti',       position: 0 },
      { id: 'di-1-2', recipeId: 'demo-1', qty: '200', unit: 'g',  item: 'guanciale',        position: 1 },
      { id: 'di-1-3', recipeId: 'demo-1', qty: '4',   unit: '',   item: 'egg yolks',        position: 2 },
      { id: 'di-1-4', recipeId: 'demo-1', qty: '80',  unit: 'g',  item: 'Pecorino Romano',  position: 3 },
    ],
    steps: [
      { id: 'ds-1-1', recipeId: 'demo-1', title: 'Boil pasta',     body: 'Cook spaghetti in well-salted water until al dente.',                               position: 0 },
      { id: 'ds-1-2', recipeId: 'demo-1', title: 'Fry guanciale',  body: 'Cook guanciale in a dry pan until crispy. Remove from heat.',                       position: 1 },
      { id: 'ds-1-3', recipeId: 'demo-1', title: 'Make sauce',     body: 'Whisk egg yolks with grated pecorino and a splash of pasta water.',                 position: 2 },
      { id: 'ds-1-4', recipeId: 'demo-1', title: 'Combine',        body: 'Off heat, toss pasta with guanciale then fold in egg mixture quickly.',             position: 3 },
    ],
  },
  {
    id: 'demo-2',
    userId: 'demo',
    title: 'Shakshuka',
    subtitle: 'Eggs poached in spiced tomato sauce',
    imageUrl: 'https://images.unsplash.com/photo-1544510807-2d87a65ae0a9?w=800&q=80',
    imageTone: '#C4603F',
    cookTime: 30,
    difficulty: 'Easy',
    tags: ['Vegetarian', 'Quick'],
    isFavorite: false,
    isPublic: false,
    createdAt: BASE,
    updatedAt: BASE,
    ingredients: [
      { id: 'di-2-1', recipeId: 'demo-2', qty: '1',   unit: 'can', item: 'crushed tomatoes', position: 0 },
      { id: 'di-2-2', recipeId: 'demo-2', qty: '4',   unit: '',    item: 'eggs',              position: 1 },
      { id: 'di-2-3', recipeId: 'demo-2', qty: '1',   unit: '',    item: 'onion',             position: 2 },
      { id: 'di-2-4', recipeId: 'demo-2', qty: '2',   unit: 'tsp', item: 'cumin',             position: 3 },
      { id: 'di-2-5', recipeId: 'demo-2', qty: '1',   unit: 'tsp', item: 'paprika',           position: 4 },
    ],
    steps: [
      { id: 'ds-2-1', recipeId: 'demo-2', title: 'Sauté onion',  body: 'Cook diced onion in olive oil until soft, about 5 min.',                     position: 0 },
      { id: 'ds-2-2', recipeId: 'demo-2', title: 'Add spices',   body: 'Add cumin and paprika, stir 1 min.',                                          position: 1 },
      { id: 'ds-2-3', recipeId: 'demo-2', title: 'Add tomatoes', body: 'Pour in crushed tomatoes, simmer 10 min until thickened.',                    position: 2 },
      { id: 'ds-2-4', recipeId: 'demo-2', title: 'Poach eggs',   body: 'Make wells in the sauce, crack eggs in. Cover and cook 5–7 min.',            position: 3 },
    ],
  },
  {
    id: 'demo-3',
    userId: 'demo',
    title: 'Banana Pancakes',
    subtitle: 'Fluffy stack with caramelised banana',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    imageTone: '#D4A24C',
    cookTime: 20,
    difficulty: 'Easy',
    tags: ['Breakfast', 'Quick'],
    isFavorite: false,
    isPublic: false,
    createdAt: BASE,
    updatedAt: BASE,
    ingredients: [
      { id: 'di-3-1', recipeId: 'demo-3', qty: '2',   unit: '',    item: 'ripe bananas',   position: 0 },
      { id: 'di-3-2', recipeId: 'demo-3', qty: '1',   unit: 'cup', item: 'flour',          position: 1 },
      { id: 'di-3-3', recipeId: 'demo-3', qty: '1',   unit: 'cup', item: 'milk',           position: 2 },
      { id: 'di-3-4', recipeId: 'demo-3', qty: '1',   unit: '',    item: 'egg',            position: 3 },
      { id: 'di-3-5', recipeId: 'demo-3', qty: '1',   unit: 'tsp', item: 'baking powder', position: 4 },
    ],
    steps: [
      { id: 'ds-3-1', recipeId: 'demo-3', title: 'Make batter', body: 'Mash bananas, mix with flour, milk, egg, and baking powder.',           position: 0 },
      { id: 'ds-3-2', recipeId: 'demo-3', title: 'Cook',        body: 'Ladle onto a hot buttered pan. Cook until bubbles form, flip once.',   position: 1 },
    ],
  },
  {
    id: 'demo-4',
    userId: 'demo',
    title: 'Avocado Toast',
    subtitle: 'Toasted sourdough with smashed avocado',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80',
    imageTone: '#7A9A5F',
    cookTime: 10,
    difficulty: 'Easy',
    tags: ['Vegetarian', 'Breakfast', 'Quick'],
    isFavorite: false,
    isPublic: false,
    createdAt: BASE,
    updatedAt: BASE,
    ingredients: [
      { id: 'di-4-1', recipeId: 'demo-4', qty: '2',   unit: 'slices', item: 'sourdough bread',    position: 0 },
      { id: 'di-4-2', recipeId: 'demo-4', qty: '1',   unit: '',       item: 'ripe avocado',       position: 1 },
      { id: 'di-4-3', recipeId: 'demo-4', qty: '',    unit: '',       item: 'lemon juice',        position: 2 },
      { id: 'di-4-4', recipeId: 'demo-4', qty: '',    unit: '',       item: 'red pepper flakes',  position: 3 },
    ],
    steps: [
      { id: 'ds-4-1', recipeId: 'demo-4', title: 'Toast bread', body: 'Toast sourdough until golden and crisp.',                                 position: 0 },
      { id: 'ds-4-2', recipeId: 'demo-4', title: 'Mash avo',    body: 'Mash avocado with lemon juice, salt, and pepper.',                       position: 1 },
      { id: 'ds-4-3', recipeId: 'demo-4', title: 'Top',         body: 'Spread on toast, finish with red pepper flakes.',                        position: 2 },
    ],
  },
  {
    id: 'demo-5',
    userId: 'demo',
    title: 'Roast Chicken',
    subtitle: 'Crispy herb-butter roast with pan juices',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c8?w=800&q=80',
    imageTone: '#9B6B3F',
    cookTime: 90,
    difficulty: 'Medium',
    tags: ['Sunday slow', 'Dinner'],
    isFavorite: false,
    isPublic: false,
    createdAt: BASE,
    updatedAt: BASE,
    ingredients: [
      { id: 'di-5-1', recipeId: 'demo-5', qty: '1.5', unit: 'kg', item: 'whole chicken',          position: 0 },
      { id: 'di-5-2', recipeId: 'demo-5', qty: '60',  unit: 'g',  item: 'butter, softened',       position: 1 },
      { id: 'di-5-3', recipeId: 'demo-5', qty: '4',   unit: '',   item: 'garlic cloves',          position: 2 },
      { id: 'di-5-4', recipeId: 'demo-5', qty: '',    unit: '',   item: 'fresh thyme and rosemary', position: 3 },
    ],
    steps: [
      { id: 'ds-5-1', recipeId: 'demo-5', title: 'Prep',  body: 'Mix butter with crushed garlic and herbs. Rub under and over skin. Season generously.', position: 0 },
      { id: 'ds-5-2', recipeId: 'demo-5', title: 'Roast', body: 'Roast at 200°C for 1h 20min, basting halfway through.',                                 position: 1 },
      { id: 'ds-5-3', recipeId: 'demo-5', title: 'Rest',  body: 'Rest 15 min before carving. Use pan juices as sauce.',                                   position: 2 },
    ],
  },
]
